// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logs() {
  return window['go']['client']['WailsApp']['Logs']();
}

export function Restart(arg1) {
  return window['go']['client']['WailsApp']['Restart'](arg1);
}

export function Stop() {
  return window['go']['client']['WailsApp']['Stop']();
}
