// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';

export function Logs():Promise<client.WailsResult>;

export function Restart(arg1:string):Promise<client.WailsResult>;

export function Stop():Promise<client.WailsResult>;
