// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logs():Promise<Array<string>>;

export function Restart(arg1:string):Promise<string>;

export function Stop():Promise<void>;
