// Code generated by "stringer -type=PackType"; DO NOT EDIT.

package transform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PackType_Dial-1]
	_ = x[PackType_Data-2]
	_ = x[PackType_CloseWrite-3]
	_ = x[PackType_Close-4]
}

const _PackType_name = "PackType_DialPackType_DataPackType_CloseWritePackType_Close"

var _PackType_index = [...]uint8{0, 13, 26, 45, 59}

func (i PackType) String() string {
	i -= 1
	if i >= PackType(len(_PackType_index)-1) {
		return "PackType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PackType_name[_PackType_index[i]:_PackType_index[i+1]]
}
