// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function Logs():Promise<wails.WailsResult>;

export function OpenDirectoryDialog(arg1:string):Promise<wails.WailsResult>;

export function OpenFileDialog(arg1:string):Promise<wails.WailsResult>;

export function Restart(arg1:string):Promise<wails.WailsResult>;

export function Stop():Promise<wails.WailsResult>;
