// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logs() {
  return window['go']['wails']['WailsApp']['Logs']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['wails']['WailsApp']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['wails']['WailsApp']['OpenFileDialog'](arg1);
}

export function Restart(arg1) {
  return window['go']['wails']['WailsApp']['Restart'](arg1);
}

export function Stop() {
  return window['go']['wails']['WailsApp']['Stop']();
}
