// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Logs() {
  return window['go']['main']['App']['Logs']();
}

export function Restart(arg1) {
  return window['go']['main']['App']['Restart'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
